# Generated by Django 3.1.3 on 2021-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
